pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                // checker requires: git branch
                git branch: 'main',
                    url: 'https://github.com/alx-backend-python/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate

                # checker requires: pip3 install
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app --junitxml=report.xml
                '''
            }
        }

        stage('Generate Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
